use_frameworks!

target 'StargateApp' do

platform :osx, '10.10'

pod 'Stargate', :path => '..'
pod 'PeerKit', :git => 'git@github.com:neonichu/PeerKit.git', :branch => 'swift2.0'

end

target 'StargateExample' do

platform :ios, '8.0'

pod 'Stargate', :path => '..'
pod 'PeerKit', :git => 'git@github.com:neonichu/PeerKit.git', :branch => 'swift2.0'

end

target 'StargateExample WatchKit Extension' do

platform :ios, '8.0'

pod 'Stargate', :path => '..'
pod 'PeerKit', :git => 'git@github.com:neonichu/PeerKit.git', :branch => 'swift2.0'

end
