use_frameworks!

target 'StargateApp' do

platform :osx, '10.10'

pod 'Stargate', :path => '..'

end

target 'StargateExample' do

platform :ios, '8.0'

pod 'Stargate', :path => '..'

end

target 'StargateExample WatchKit Extension' do

platform :ios, '8.0'

pod 'Stargate', :path => '..'

end
